### ISSUE TITLE
AddItem and RemoveItem tests poorly written

### ISSUE THREAD

**Issue by jacob-israel-turner** [DevMountain/JS-Arrays#13]
The instructions state that `addItem` and `removeItem` will be called with two arguments, an array and an item to add/remove from the array.  The `should return an array` tests don't call these functions with any arguments, so the functions usually fail.  A better test would be something along the following lines:

```
it('should return an array', function () {
  expect(addItem(['chips'], 'MtnDew')).toEqual(jasmine.any(Array));
})
```

**Comment by asBrettisay** [comment]
Fixed in #22.
